# Generated by Django 2.2.3 on 2019-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
    ]
