# Generated by Django 2.2.3 on 2019-07-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190725_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=255, verbose_name='Gênero'),
        ),
    ]
