# Generated by Django 2.2.3 on 2019-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ideia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='password',
            field=models.CharField(max_length=225, verbose_name='password'),
        ),
    ]
